export { wipeLocalUserData } from "./wipe-local";
export { DATABASE_NAME, DATABASE_VERSION } from "./constants";
export {
  migrateDbIfNeeded,
  ensureDailySummarySchema,
  ensureXpSchema,
  ensureSavedMealsSchema,
  ensurePrefsProfileSchema,
} from "./migrations";
export {
  DAILY_GOAL_LIMITS,
  DEFAULT_DAILY_GOALS,
  getDailyGoals,
  setDailyGoals,
  waterAmountLimits,
  WATER_UNITS,
  weightGoalLimits,
  WEIGHT_UNITS,
  type DailyGoals,
  type DailyGoalsUpdate,
  type WaterUnit,
  type WeightUnit,
} from "./daily-goals";
export {
  computeGoalsMet,
  DAILY_SUMMARY_GOAL_KEYS,
  getDailySummary,
  getEarliestActiveKcalDayKey,
  getEarliestFoodDayKey,
  getEarliestSleepDayKey,
  getEarliestStepsDayKey,
  getEarliestTrainDayKey,
  getEarliestWaterDayKey,
  getEarliestWeightDayKey,
  getActiveKcalHistorySeries,
  getFoodHistorySeries,
  getFoodKcalHistorySeries,
  getSleepHistorySeries,
  getStepsHistorySeries,
  getTrainHistorySeries,
  getWaterHistorySeries,
  getWeightHistorySeries,
  getMonthlyWeightSeries,
  getTodayDailySummary,
  getWeeklyMetricSeries,
  invalidateDailySummary,
  listDailySummariesForDayKeys,
  listDayKeysEndingAt,
  listMonthKeysEndingAt,
  monthDayLabelForDayKey,
  monthKeyFromDayKey,
  monthShortLabelForMonthKey,
  recomputeDailySummary,
  shiftDayKey,
  shiftMonthKey,
  weekStartDayKey,
  weekdayShortLabelForDayKey,
  yearFromDayKey,
  type DailySummary,
  type DailySummaryGoalKey,
  type DailySummaryTotalsOptions,
  type ActiveKcalHistorySeries,
  type FoodHistorySeries,
  type FoodKcalHistorySeries,
  type FoodKcalHistorySpec,
  type SleepHistorySeries,
  type StepsHistorySeries,
  type TrainHistorySeries,
  type WaterHistorySeries,
  type WeightHistorySeries,
  type HabitSummaryMetric,
  type MonthlyWeightSeries,
  type WeeklyMetricSeries,
} from "./daily-summary";
export {
  DAY_STARTS_AT_MINUTES_MAX,
  DAY_STARTS_AT_MINUTES_MIN,
  DEFAULT_DAY_STARTS_AT_MINUTES,
  formatDayKeyInTimeZone,
  getAppDayKey,
  getDayBoundary,
  getDeviceTimeZone,
  getLocalDayKey,
  getTodayDayKey,
  setDayBoundary,
  type DayBoundary,
  type DayBoundaryUpdate,
  type SetDayBoundaryOptions,
} from "./day-boundary";
export {
  APP_THEME_CATALOG,
  APP_THEME_IDS,
  DEFAULT_APP_PREFS,
  DEFAULT_THEME_ID,
  getPrefs,
  getThemeDefinition,
  isAppThemeId,
  PREFS_LIMITS,
  setPrefs,
  UNIT_SYSTEMS,
  unlockTheme,
  type AppPrefs,
  type AppPrefsUpdate,
  type AppThemeDefinition,
  type AppThemeId,
  type UnitSystem,
} from "./prefs";
export {
  DEFAULT_APP_PROFILE,
  getProfile,
  PROFILE_DISPLAY_NAME_FALLBACK,
  PROFILE_LIMITS,
  setProfile,
  type AppProfile,
  type AppProfileUpdate,
} from "./profile";
export {
  aggregateHabitLogs,
  convertWaterAmount,
  convertWeightValue,
  DEFAULT_RECENT_FOOD_MEALS_LIMIT,
  FOOD_MEAL_TYPES,
  getHabitLog,
  getHabitTotalsForDayKey,
  getLatestWeightValue,
  getTodayHabitTotals,
  HABIT_LOG_LIMITS,
  HABIT_LOG_SOURCES,
  HABIT_LOG_TYPES,
  insertHabitLog,
  listHabitLogsForDay,
  listRecentFoodMeals,
  logActiveKcal,
  logFood,
  logSleep,
  logSteps,
  logTrain,
  logWater,
  logWeight,
  waterHabitAmountLimits,
  weightHabitValueLimits,
  type ActiveKcalHabitPayload,
  type FoodHabitPayload,
  type FoodMealType,
  type HabitDayTotals,
  type HabitDayTotalsOptions,
  type HabitLog,
  type HabitLogInsertInput,
  type HabitLogPayloadByType,
  type HabitLogSource,
  type HabitLogType,
  type RecentFoodMeal,
  type SleepHabitPayload,
  type StepsHabitPayload,
  type TrainHabitPayload,
  type WaterHabitPayload,
  type WeightHabitPayload,
} from "./habit-log";
export { newLocalRecord, nowIso, uuid } from "./ids";
export {
  acknowledgeOpRejected,
  acknowledgeOpSynced,
  enqueueOp,
  FACT_PENDING_OP_TYPES,
  getPendingOp,
  listDrainableOps,
  markOpFailed,
  PENDING_OP_SCHEMA_VERSION,
  PENDING_SERVER_OP_STATUSES,
  PENDING_SERVER_OP_TYPES,
  sanitizePendingOpPayload,
  subscribePendingOpEnqueue,
  trustForOpType,
  type EnqueueOpOptions,
  type PendingServerOp,
  type PendingServerOpStatus,
  type PendingServerOpTrust,
  type PendingServerOpType,
} from "./pending-ops";
export type { LocalRecord } from "./types";
export {
  deleteSavedMeal,
  findSavedMealByContent,
  getSavedMeal,
  listSavedMeals,
  savedMealContentKey,
  upsertSavedMeal,
  type SavedMeal,
  type SavedMealDeletePayload,
  type SavedMealInput,
} from "./saved-meals";
export {
  applyXpAward,
  awardXp,
  claimGoalBonusSlot,
  DAY_COMPLETE_BONUS_KEY,
  getXpState,
  hasGoalBonusBeenAwarded,
  listRecentXpEvents,
  maybeAwardGoalBonusesForDay,
  XP_DAY_COMPLETE,
  XP_EVENT_REASONS,
  XP_PER_GOAL_MET,
  XP_PER_HABIT_LOG,
  type AwardXpInput,
  type GoalBonusAwardResult,
  type XpEvent,
  type XpEventReason,
  type XpState,
} from "./xp";
